kobocat/onadata/apps/api/urls.py
from django.conf.urls import url
from rest_framework import routers
from rest_framework.response import Response
from rest_framework.reverse import reverse
from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework.views import APIView

from onadata.apps.api.viewsets.charts_viewset import ChartsViewSet
from onadata.apps.api.viewsets.connect_viewset import ConnectViewSet
from onadata.apps.api.viewsets.data_viewset import DataViewSet
from onadata.apps.api.viewsets.metadata_viewset import MetaDataViewSet
from onadata.apps.api.viewsets.note_viewset import NoteViewSet
from onadata.apps.api.viewsets.organization_profile_viewset import\
    OrganizationProfileViewSet
from onadata.apps.api.viewsets.project_viewset import ProjectViewSet
from onadata.apps.api.viewsets.stats_viewset import StatsViewSet
from onadata.apps.api.viewsets.team_viewset import TeamViewSet
from onadata.apps.api.viewsets.xform_viewset import XFormViewSet
from onadata.apps.api.viewsets.user_profile_viewset import UserProfileViewSet
from onadata.apps.api.viewsets.user_viewset import UserViewSet
from onadata.apps.api.viewsets.submissionstats_viewset import\
    SubmissionStatsViewSet
from onadata.apps.api.viewsets.attachment_viewset import AttachmentViewSet
from onadata.apps.api.viewsets.xform_list_api import XFormListApi
from onadata.apps.api.viewsets.xform_submission_api import XFormSubmissionApi
from onadata.apps.api.viewsets.briefcase_api import BriefcaseApi


def make_routes(template_text):
    return routers.Route(
        url=r'^{prefix}/{%s}{trailing_slash}$' % template_text,
        mapping={
            'get': 'list',
            'post': 'create'
        },
        name='{basename}-list',
        initkwargs={'suffix': 'List'})


class MultiLookupRouter(routers.DefaultRouter):
    def __init__(self, *args, **kwargs):
        super(MultiLookupRouter, self).__init__(*args, **kwargs)
        self.lookups_routes = []
        self.lookups_routes.append(routers.Route(
            url=r'^{prefix}/{lookups}{trailing_slash}$',
            mapping={
                'get': 'retrieve',
                'put': 'update',
                'patch': 'partial_update',
                'delete': 'destroy'
            },
            name='{basename}-detail',
            initkwargs={'suffix': 'Instance'}
        ))
        self.lookups_routes.append(make_routes('lookup'))
        self.lookups_routes.append(make_routes('lookups'))
        # Dynamically generated routes.
        # Generated using @action or @link decorators on methods of the viewset
        self.lookups_routes.append(routers.Route(
            url=[
                r'^{prefix}/{lookups}/{methodname}{trailing_slash}$',
                r'^{prefix}/{lookups}/{methodname}/{extra}{trailing_slash}$'],
            mapping={
                '{httpmethod}': '{methodname}',
            },
            name='{basename}-{methodnamehyphen}',
            initkwargs={}
        ))

    def get_extra_lookup_regexes(self, route):
        ret = []
        base_regex = '(?P<{lookup_field}>[^/]+)'
        if 'extra_lookup_fields' in route.initkwargs:
            for lookup_field in route.initkwargs['extra_lookup_fields']:
                ret.append(base_regex.format(lookup_field=lookup_field))
        return '/'.join(ret)

    def get_lookup_regexes(self, viewset):
        ret = []
        lookup_fields = getattr(viewset, 'lookup_fields', None)
        if lookup_fields:
            for i in range(1, len(lookup_fields)):
                tmp = []
                for lookup_field in lookup_fields[:i + 1]:
                    if lookup_field == lookup_fields[i]:
                        base_regex = '(?P<{lookup_field}>[^/.]+)'
                    else:
                        base_regex = '(?P<{lookup_field}>[^/]+)'
                    tmp.append(base_regex.format(lookup_field=lookup_field))
                ret.append(tmp)
        return ret

    def get_lookup_routes(self, viewset):
        ret = [self.routes[0]]
        # Determine any `@action` or `@link` decorated methods on the viewset
        dynamic_routes = []
        for methodname in dir(viewset):
            attr = getattr(viewset, methodname)
            httpmethods = getattr(attr, 'bind_to_methods', None)
            if httpmethods:
                httpmethods = [method.lower() for method in httpmethods]
                dynamic_routes.append((httpmethods, methodname))

        for route in self.lookups_routes:
            if route.mapping == {'{httpmethod}': '{methodname}'}:
                # Dynamic routes (@link or @action decorator)
                for httpmethods, methodname in dynamic_routes:
                    initkwargs = route.initkwargs.copy()
                    initkwargs.update(getattr(viewset, methodname).kwargs)
                    mapping = dict(
                        (httpmethod, methodname) for httpmethod in httpmethods)
                    name = routers.replace_methodname(route.name, methodname)
                    if 'extra_lookup_fields' in initkwargs:
                        uri = route.url[1]
                        uri = routers.replace_methodname(uri, methodname)
                        ret.append(routers.Route(
                            url=uri, mapping=mapping, name='%s-extra' % name,
                            initkwargs=initkwargs,
                        ))
                    uri = routers.replace_methodname(route.url[0], methodname)
                    ret.append(routers.Route(
                        url=uri, mapping=mapping, name=name,
                        initkwargs=initkwargs,
                    ))
            else:
                # Standard route
                ret.append(route)
        return ret

    def get_routes(self, viewset):
        ret = []
        lookup_fields = getattr(viewset, 'lookup_fields', None)
        if lookup_fields:
            ret = self.get_lookup_routes(viewset)
        else:
            ret = super(MultiLookupRouter, self).get_routes(viewset)
        return ret

    def get_api_root_view(self):
        """
        Return a view to use as the API root.
        """
        api_root_dict = {}
        list_name = self.routes[0].name
        for prefix, viewset, basename in self.registry:
            api_root_dict[prefix] = list_name.format(basename=basename)

        class OnaApi(APIView):
            """
## KoBo JSON Rest API endpoints:

### Data
* [/api/v1/charts](/api/v1/charts) - List, Retrieve Charts of collected data
* [/api/v1/data](/api/v1/data) - List, Retrieve submission data
* [/api/v1/stats](/api/v1/stats) - Summary statistics

### Forms
* [/api/v1/forms](/api/v1/forms) - List, Retrieve form information
* [/api/v1/media](/api/v1/media) - List, Retrieve media attachments
* [/api/v1/metadata](/api/v1/metadata) - List, Retrieve form metadata
* [/api/v1/projects](/api/v1/projects) - List, Retrieve, Create,
 Update organization projects, forms
* [/api/v1/submissions](/api/v1/submissions) - Submit XForms to a form

### Users and Organizations
* [/api/v1/orgs](/api/v1/orgs) - List, Retrieve, Create,
Update organization and organization info
* [/api/v1/profiles](/api/v1/profiles) - List, Create, Update user information
* [/api/v1/teams](/api/v1/teams) - List, Retrieve, Create, Update teams
* [/api/v1/user](/api/v1/user) - Return authenticated user profile info
* [/api/v1/users](/api/v1/users) - List, Retrieve user data

## Status Codes

* **200** - Successful [`GET`, `PATCH`, `PUT`]
* **201** - Resource successfully created [`POST`]
* **204** - Resouce successfully deleted [`DELETE`]
* **403** - Permission denied to resource
* **404** - Resource was not found

## Authentication

KoBo JSON API enpoints support both Basic authentication
and API Token Authentication through the `Authorization` header.

### Basic Authentication

Example using curl:

    curl -X GET https://example.com/api/v1/ -u username:password

### Token Authentication

Example using curl:

    curl -X GET https://example.com/api/v1/ -H "Authorization: Token TOKEN_KEY"

### KoBo Tagging API

* [Filter form list by tags.](
/api/v1/forms#get-list-of-forms-with-specific-tags)
* [List Tags for a specific form.](
/api/v1/forms#get-list-of-tags-for-a-specific-form)
* [Tag Forms.](/api/v1/forms#tag-forms)
* [Delete a specific tag.](/api/v1/forms#delete-a-specific-tag)
* [List form data by tag.](
/api/v1/data#query-submitted-data-of-a-specific-form-using-tags)
* [Tag a specific submission](/api/v1/data#tag-a-submission-data-point)

## Using Oauth2 with the KoBo API

You can learn more about oauth2 [here](
http://tools.ietf.org/html/rfc6749).

### 1. Register your client application with KoBo - [register](\
/o/applications/register/)

- `name` - name of your application
- `client_type` - Client Type: select confidential
- `authorization_grant_type` - Authorization grant type: Authorization code
- `redirect_uri` - Redirect urls: redirection endpoint

Keep note of the `client_id` and the `client_secret`, it is required when
 requesting for an `access_token`.

### 2. Authorize client application.

The authorization url is of the form:

<pre class="prettyprint">
<b>GET</b> /o/authorize?client_id=XXXXXX&response_type=code&state=abc</pre>

example:

    http://localhost:8000/o/authorize?client_id=e8&response_type=code&state=xyz

Note: Providing the url to any user will prompt for a password and
request for read and write permission for the application whose `client_id` is
specified.

Where:

- `client_id` - is the client application id - ensure its urlencoded
- `response_type` - should be code
- `state` - a random state string that you client application will get when
   redirection happens

What happens:

1. a login page is presented, the username used to login determines the account
   that provides access.
2. redirection to the client application occurs, the url is of the form:

>   REDIRECT_URI/?state=abc&code=YYYYYYYYY

example redirect uri

kobocat/onadata/apps/approval/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'approval.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

kobocat/onadata/apps/scheduling/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'scheduling.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

kobocat/onadata/apps/unicef/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from onadata.apps.unicef import views

urlpatterns = patterns('',
    # url(r'^$', views.index, name='index'),
    url(r'^geodata/$', views.geo_index, name='geo_index'),
    url(r'^add-geodata/$', views.add_geodata, name='add_geodata'),
    url(r'^geo-edit/(?P<geo_id>\d+)/$', views.edit_geodata, name='edit_geodata'),
    url(r'^geo-delete/(?P<geo_id>\d+)/$', views.delete_geodata, name='delete_geodata'),
    
    url(r'^geo-rmo-list/$', views.rmo_index, name='rmo_index'),
    url(r'^add-geo-rmo/$', views.add_geo_rmo, name='add_geo_rmo'),
    url(r'^geo-edit-rmo/(?P<rmo_id>\d+)/$', views.edit_geo_rmo, name='edit_geo_rmo'),
    url(r'^geo-delete-rmo/(?P<rmo_id>\d+)/$', views.delete_geo_rmo, name='delete_geo_rmo'),

    url(r'^geo-psu-list/$', views.psu_index, name='psu_index'),
    url(r'^add-geo-psu/$', views.add_geo_psu, name='add_geo_psu'),
    url(r'^geo-edit-psu/(?P<psu_id>\d+)/$', views.edit_geo_psu, name='edit_geo_psu'),
    url(r'^geo-delete-psu/(?P<psu_id>\d+)/$', views.delete_geo_psu, name='delete_geo_psu'),
    # ajax url
    url(r'^get-children/$', views.get_children, name='get_children'),
    url(r'^get-object/$', views.dynamic_ajax, name='dynamic_ajax'),

    url(r'^data/$', views.data_view_project, name='data_view_project'),
    url(r'^unicef_dashboard/$', views.create_dashboard, name='unicef_dashboard'),
    url(r'^unicef_br_report/$', views.create_br_report, name='unicef_br_report'),
    url(r'^get-options/$', views.get_options, name='get_options'),
    
    
    )

kobocat/onadata/apps/unicef/models.py
from django.db import models
from django.contrib.auth.models import User


class GeoTable(models.Model):
    NA= 'NA'
    DIVISION = 'DV'
    DISTRICT = 'DC'
    UPAZILLA = 'UP'
    UNION = 'UN'
    VILLAGE = 'VL'
    TYPES = (
        (NA, 'Select a Type'),
        (DIVISION, 'Division'),
        (DISTRICT, 'District'),
        (UPAZILLA, 'Upazilla'),
        (UNION , 'Union'),
        (VILLAGE , 'Village'),
    )
    geo_id = models.IntegerField()
    name = models.CharField(max_length=150)
    parent = models.ForeignKey('GeoTable',related_name='geo_table_parent', on_delete=models.CASCADE,blank=True,null=True)
    geo_type =  models.CharField(max_length=2,
                                      choices=TYPES,
                                      default=NA)
    # Override the __unicode__() method to return out something meaningful!
    def __str__(self):
        return self.name


class GeoPSU(models.Model):
    # user = models.ManyToManyField(User)
    psu_id = models.IntegerField()
    name = models.CharField(max_length=150)
    geo_district = models.ForeignKey('GeoTable',related_name='geo_district', on_delete=models.CASCADE,limit_choices_to={'geo_type': 'DC'},)
    geo_division = models.ForeignKey('GeoTable',related_name='geo_division', on_delete=models.CASCADE,limit_choices_to={'geo_type': 'DV'},)
    geo_upazilla = models.ForeignKey('GeoTable',related_name='geo_upazilla', on_delete=models.CASCADE,limit_choices_to={'geo_type': 'UP'},)
    geo_union = models.ForeignKey('GeoTable',related_name='geo_union', on_delete=models.CASCADE,limit_choices_to={'geo_type': 'UN'},)
    geo_rmo = models.ForeignKey('GeoRMO',related_name='geo_rmo', on_delete=models.CASCADE)
    # Override the __unicode__() method to return out something meaningful!
    def __str__(self):
        return self.name


class GeoRMO(models.Model):
    rmo_id = models.IntegerField(unique=True)
    rmo_type = models.CharField(max_length=150)
    
    def __str__(self):
        return str(self.rmo_id)

kobocat/onadata/apps/unicef/forms.py
from django import forms
# from django.forms import ModelForm, CharField, TextInput
from onadata.apps.unicef.models import GeoTable,GeoRMO,GeoPSU
import sys


class GeoForm(forms.ModelForm):
    # parent = forms.ModelChoiceField(label='Parent',queryset=GeoTable.objects.all(),empty_label="Select an Parent")
    class Meta:
        model = GeoTable
        fields = ('geo_id','name', 'geo_type', 'parent')


class GeoPSUForm(forms.Form):
    psu_id = forms.CharField(label="PSU ID", max_length=4)
    name = forms.CharField(label="PSU Name", max_length=150)
    geo_division = forms.ModelChoiceField(label='Division',required=True,queryset=GeoTable.objects.filter(geo_type='DV'),empty_label="Select a Division") 
    geo_district = forms.ModelChoiceField(label='District',required=True,queryset=GeoTable.objects.filter(geo_type='DC'),empty_label="Select a District") # 
    geo_upazilla = forms.ModelChoiceField(label='Upazilla',required=True,queryset=GeoTable.objects.filter(geo_type='UP'),empty_label="Select a Upazilla") # ,
    geo_union = forms.ModelChoiceField(label='Union',required=True,queryset=GeoTable.objects.filter(geo_type='UN'),empty_label="Select a Union")
    geo_rmo = forms.ModelChoiceField(label='RMO',required=True,queryset=GeoRMO.objects.all(),empty_label="Select a RMO") 
    
    def __init__(self, *args, **kwargs):
        geo_item = kwargs.pop('geo_item', None)
        super(GeoPSUForm, self).__init__(*args, **kwargs)
        if geo_item is not None:
            self.fields['psu_id'].initial = geo_item.psu_id
            self.fields['name'].initial = geo_item.name
            self.fields['geo_division'].initial = geo_item.geo_division
            self.fields['geo_district'].initial = geo_item.geo_district
            self.fields['geo_upazilla'].initial = geo_item.geo_upazilla
            self.fields['geo_union'].initial = geo_item.geo_union
            self.fields['geo_rmo'].initial = geo_item.geo_rmo
    
    def clean_psu_id(self):
        psu_id = self.cleaned_data.get('psu_id')
        try:
            psu_id = int(psu_id)
        except ValueError:
            raise forms.ValidationError('PSU Id must be an integer')
        if psu_id and len(str(psu_id)) < 4:
            raise forms.ValidationError('PSU Id must have 4 digits')
        return self.cleaned_data


class GeoRMOForm(forms.Form):
    rmo_id = forms.CharField(label="RMO ID", max_length=4)
    rmo_type = forms.CharField(label="RMO Type", max_length=100)
    
    def clean_rmo_id(self):
        rmo_id = self.cleaned_data.get('rmo_id')
        try:
            rmo_id = int(rmo_id)
        except ValueError:
            raise forms.ValidationError('RMO Id must be an integer')
        if rmo_id and len(str(rmo_id)) < 4:
            raise forms.ValidationError('RMO Id must have 4 digits')
        return self.cleaned_data

kobocat/onadata/apps/unicef/templates/unicef/add_geodata.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<section id="data-view">
    <h1>Add a Geo Item</h1>
    {% if is_added %}
    <div class="alert alert-success" role="alert">
        Added successfully
    </div>

    <form action="/unicef/geodata">
        <input type="submit" class="btn btn-success" value="Return to Geo Data">
    </form>
    {% else %}
    
    <span class="span12">
        <div class="data-table-container table table-striped table-hover">
            <form id="user_form" method="post" action="/unicef/add-geodata/">
                {% csrf_token %}
                {{ geo_form.as_p }}
                <input type="submit"  class="btn btn-primary btn-lg" name="submit" value="Save" />
            </form>
            
            <div style="clear: both;"></div>
        </div>
    </span>
    {% endif %}
</section>
{% endblock %}

kobocat/onadata/apps/unicef/templates/unicef/add_psu.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<section id="data-view">
    <h1>Add a PSU</h1>
    {% if is_added %}
    <div class="alert alert-success" role="alert">
        Added successfully
    </div>

    <form action="/unicef/geo-psu-list">
        <input type="submit" class="btn btn-success" value="Return to RMO List">
    </form>
    {% else %}
    
    <span class="span12">
        <div class="data-table-container table table-striped table-hover">
            <form id="user_form" method="post" action="/unicef/add-geo-psu/">
                {% csrf_token %}
                {{ geo_psu_form.as_p }}
                <input type="submit"  class="btn btn-primary btn-lg" name="submit" value="Save" />
            </form>
            
            <div style="clear: both;"></div>
        </div>
    </span>
    {% endif %}
</section>
{% endblock %}

{% block additional-javascript %}
<script type="text/javascript">

$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            var csrftoken = getCookie('csrftoken');
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
});


$("#id_geo_division, #id_geo_district").change(function() {
    var geo_id = $(this).attr("value");
    var dropdown = '';
    var message = '';
    selector = $(this).attr("id");
    if (geo_id){
        $.ajax({
            type: "POST",
            url:"/unicef/get-children/",
            data: {id: geo_id},
            success: function(data){

                if( selector === 'id_geo_division'){
                    dropdown = '#id_geo_district' ;
                    message = "Select a District" ;
                }else if ( selector === 'id_geo_district'){
                    dropdown = '#id_geo_upazilla' ;
                    message = "Select a Upazilla" ;
                }
                console.log(dropdown);
                $(dropdown).empty();
                $(dropdown).append(
                    '<option value="">'+message+'</option>'
                );
                if (data.length > 0){
                    data.forEach(function(option) {
                        $(dropdown).append(
                            '<option value="'+option.id+'">'+option.name+'</option>'
                        );
                    });
                }
            },
            error: function(){
            
            } 
        }) // end-ajax
    }
});

function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie != '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) == (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}

function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
</script>
{% endblock %}

kobocat/onadata/apps/unicef/templates/unicef/add_rmo.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<section id="data-view">
    <h1>Add a RMO</h1>
    {% if is_added %}
    <div class="alert alert-success" role="alert">
        Added successfully
    </div>

    <form action="/unicef/geo-rmo-list">
        <input type="submit" class="btn btn-success" value="Return to RMO List">
    </form>
    {% else %}
    
    <span class="span12">
        <div class="data-table-container table table-striped table-hover">
            <form id="user_form" method="post" action="/unicef/add-geo-rmo/">
                {% csrf_token %}
                {{ geo_rmo_form.as_p }}
                <input type="submit"  class="btn btn-primary btn-lg" name="submit" value="Save" />
            </form>
            
            <div style="clear: both;"></div>
        </div>
    </span>
    {% endif %}
</section>
{% endblock %}

kobocat/onadata/apps/unicef/templates/unicef/edit_geo_psu.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<section id="data-view">
    <h1>Edit Geo Item</h1>
    {% if edited %}
    <div class="alert alert-success" role="alert">
        Editing successful
    </div>

    <form action="/unicef/geo-psu-list">
        <input type="submit" class="btn btn-success" value="Return to PSU Data">
    </form>
    {% else %}
    
    <span class="span12">
        <div class="data-table-container table table-striped table-hover">
            <form id="edit_form" method="post" action="/unicef/geo-edit-psu/{{id}}/">
                {% csrf_token %}
                {{ geo_psu_form.as_p }}
                <input type="submit"  class="btn btn-primary btn-lg" name="submit" value="Save" />
            </form>
            
            <div style="clear: both;"></div>
        </div>
    </span>
    {% endif %}
</section>
{% endblock %}

{% block additional-javascript %}
<script type="text/javascript">

$( document ).ready(function(){
    dropdown = "#id_geo_district";
    geo_id = $("#id_geo_division").val();
    selected_district = $(dropdown).val();
    selected_upazilla = $("#id_geo_upazilla").val();
    $.ajax({
        type: "POST",
        url:"/unicef/get-children/",
        data: {id: geo_id},
        success: function(data){
            message = "Select a District" ;
            $(dropdown).empty();
            $(dropdown).append(
                '<option value="">'+message+'</option>'
            );
            if (data.length > 0){
                data.forEach(function(option) {
                    $(dropdown).append(
                        '<option value="'+option.id+'">'+option.name+'</option>'
                    );
                });
            }
            $(dropdown).val(selected_district);
        },
        error: function(){
        } 
    }) // end-ajax
    dropdown_upazilla = "#id_geo_upazilla";
    $.ajax({
        type: "POST",
        url:"/unicef/get-children/",
        data: {id: selected_district},
        success: function(data){
            message = "Select a Upazilla" ;
            $(dropdown_upazilla).empty();
            $(dropdown_upazilla).append(
                '<option value="">'+message+'</option>'
            );
            if (data.length > 0){
                data.forEach(function(option) {
                    $(dropdown_upazilla).append(
                        '<option value="'+option.id+'">'+option.name+'</option>'
                    );
                });
            }
            $(dropdown_upazilla).val(selected_upazilla);
        },
        error: function(){
        } 
    }) // end-ajax

});

$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            var csrftoken = getCookie('csrftoken');
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
});


$("#id_geo_division, #id_geo_district").change(function() {
    var geo_id = $(this).attr("value");
    var dropdown = '';
    var message = '';
    selector = $(this).attr("id");
    if (geo_id){
        $.ajax({
            type: "POST",
            url:"/unicef/get-children/",
            data: {id: geo_id},
            success: function(data){

                if( selector === 'id_geo_division'){
                    dropdown = '#id_geo_district' ;
                    message = "Select a District" ;
                }else if ( selector === 'id_geo_district'){
                    dropdown = '#id_geo_upazilla' ;
                    message = "Select a Upazilla" ;
                }
                console.log(dropdown);
                $(dropdown).empty();
                $(dropdown).append(
                    '<option value="">'+message+'</option>'
                );
                if (data.length > 0){
                    data.forEach(function(option) {
                        $(dropdown).append(
                            '<option value="'+option.id+'">'+option.name+'</option>'
                        );
                    });
                }
            },
            error: function(){
            
            } 
        }) // end-ajax
    }
});

function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie != '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) == (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}

function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
</script>
{% endblock %}

kobocat/onadata/apps/unicef/templates/unicef/edit_geo_rmo.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<section id="data-view">
    <h1>Edit Geo Item</h1>
    {% if edited %}
    <div class="alert alert-success" role="alert">
        Editing successful
    </div>

    <form action="/unicef/geo-rmo-list">
        <input type="submit" class="btn btn-success" value="Return to Geo Data">
    </form>
    {% else %}
    
    <span class="span12">
        <div class="data-table-container table table-striped table-hover">
            <form id="edit_form" method="post" action="/unicef/geo-edit-rmo/{{id}}/">
                {% csrf_token %}
                {{ geo_rmo_form.as_p }}
                <input type="submit"  class="btn btn-primary btn-lg" name="submit" value="Save" />
            </form>
            
            <div style="clear: both;"></div>
        </div>
    </span>
    {% endif %}
</section>
{% endblock %}

kobocat/onadata/apps/unicef/templates/unicef/edit_geoitem.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<section id="data-view">
    <h1>Edit Geo Item</h1>
    {% if edited %}
    <div class="alert alert-success" role="alert">
        Editing successful
    </div>

    <form action="/unicef/geodata">
        <input type="submit" class="btn btn-success" value="Return to Geo Data">
    </form>
    {% else %}
    
    <span class="span12">
        <div class="data-table-container table table-striped table-hover">
            <form id="edit_form" method="post" action="/unicef/geo-edit/{{id}}/">
                {% csrf_token %}
                {{ geo_form.as_p }}
                <input type="submit"  class="btn btn-primary btn-lg" name="submit" value="Save" />
            </form>
            
            <div style="clear: both;"></div>
        </div>
    </span>
    {% endif %}
</section>
{% endblock %}